// Generated by CoffeeScript 1.4.0
(function() {
  var Whiskey2;

  yepnope({
    load: ['lib/jquery-1.8.2.min.js', 'bs/css/bootstrap.min.css', 'bs/js/bootstrap.min.js', 'lib/custom-web/date.js', 'lib/custom-web/cross-utils.js', 'lib/common-web/underscore-min.js', 'lib/common-web/underscore.strings.js', 'css/whiskey2.css', 'lib/lima1/net.js', 'lib/lima1/main.js'],
    complete: function() {
      return $(document).ready(function() {
        var app;
        app = new Whiskey2;
        return app.start();
      });
    }
  });

  Whiskey2 = (function() {

    function Whiskey2() {}

    Whiskey2.prototype.start = function() {
      var db, jqnet, manager, oauth, storage;
      db = new HTML5Provider('app.db', '1');
      storage = new StorageProvider(db);
      jqnet = new jQueryTransport('http://lima1-kvj.rhcloud.com');
      oauth = new OAuthProvider({
        clientID: 'whiskey2web'
      }, jqnet);
      manager = new Lima1DataManager('whiskey2', oauth, storage);
      return oauth.token = manager.get('token');
    };

    return Whiskey2;

  })();

}).call(this);
